### ISSUE TITLE
Implementation reference

### ISSUE THREAD

**Issue by jay-reynolds** [cpearce/riptree#1]
Hi, I arrived here after realizing that for my data, I was only discovering obvious rules with Apriori, and digging deep into rare rule territory was costing enormously in terms of memory and runtime.

Just playing with your code and ran a few tests -- it's incredibly fast!

Is this paper appropriate for me to read to better understand the algorithm you've implemented?  (I notice the work was done at the U. of Auckland, so seemed like a good bet)

https://link.springer.com/chapter/10.1007/978-3-642-23544-3_21

Thank you very much for your time and any direction you can offer.

**Comment by cpearce** [comment]
Hi Jay. Thanks for the complements. :)

The algorithm used in this code was never actually published in a paper, so I don't recommend you base work on it.

I recommend you look at and/or use the code in my arm-rs repository:
https://github.com/cpearce/arm-rs

My arm-rs repository is a general purpose implementation of FP-Growth, unlike the code in this repository which is specialized. I heavily profiled and optimized the arm-rs code, to the point now that it's completely IO bound; it generates billions of rules in milliseconds, way faster than they can be written to disk.

The RP Tree paper you link to will give you some insights into rare pattern mining, but also for a good survey of rare pattern mining you can checkout this paper:
https://dl.acm.org/doi/pdf/10.1145/2898359

**Comment by jay-reynolds** [comment]
Very excited to check out arm-rs and the paper you recommend!
Thank you again.
